// <auto-generated />
using System;
using BankApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankApi.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260312142209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankApi.Services.Program+KontoBankowe", b =>
                {
                    b.Property<string>("NumerKonta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Wlasciciel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumerKonta");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApi.Services.Program+Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataTransakcji")
                        .HasColumnType("datetime2");

                    b.Property<string>("KontoBankoweNumerKonta")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Kwota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumerKontaNadawcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumerKontaOdbiorcy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KontoBankoweNumerKonta");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankApi.Services.Program+Transaction", b =>
                {
                    b.HasOne("BankApi.Services.Program+KontoBankowe", null)
                        .WithMany("Transakcje")
                        .HasForeignKey("KontoBankoweNumerKonta");
                });

            modelBuilder.Entity("BankApi.Services.Program+KontoBankowe", b =>
                {
                    b.Navigation("Transakcje");
                });
#pragma warning restore 612, 618
        }
    }
}
