// <auto-generated />
using System;
using BankApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankApi.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BankApi.Services.Program+KontoBankowe", b =>
                {
                    b.Property<string>("NumerKonta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wlasciciel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NumerKonta");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApi.Services.Program+Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataTransakcji")
                        .HasColumnType("TEXT");

                    b.Property<string>("KontoBankoweNumerKonta")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerKontaNadawcy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerKontaOdbiorcy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KontoBankoweNumerKonta");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankApi.Services.Program+Transaction", b =>
                {
                    b.HasOne("BankApi.Services.Program+KontoBankowe", null)
                        .WithMany("Transakcje")
                        .HasForeignKey("KontoBankoweNumerKonta");
                });

            modelBuilder.Entity("BankApi.Services.Program+KontoBankowe", b =>
                {
                    b.Navigation("Transakcje");
                });
#pragma warning restore 612, 618
        }
    }
}
